---
title: "hw8"
author: "Abby Bergman"
date: "11/22/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(tidyverse)
library(gapminder)
library(geonames)
library(tibble)
library(dplyr)
library(countrycode)
library(rjson)
library(rvest)
library(knitr)
library(ggplot2)
```

#Part 1: Exploring Population Density

```{r, include=FALSE}
#get geonames
options(geonamesUsername="abbygirlrose")
options(geonamesHost="api.geonames.org")


geonamesinfo <- GNcountryInfo() %>%
  as.data.frame()


```


```{r, include = FALSE, message=FALSE, warning=FALSE}
#changing country code
geonamesinfo$country <- countrycode(pull(geonamesinfo,countryCode) , 'iso2c', 'country.name')

geonamesinfo %>%
  select("country", "areaInSqKm") 

#left join to one data set
combined <- left_join(gapminder, geonamesinfo, by = "country")

#make popden column
combined1 <- combined %>%
  mutate(popden = pop/as.numeric(areaInSqKm))
```

```{r, echo=FALSE}
#graph to compare popden and lifexp

combined1 %>%
  ggplot(aes(popden, lifeExp)) +
  geom_jitter(alpha = .2) +
  geom_smooth() +
  scale_x_log10() +
  labs(title = "Population Density vs Life Expectancy", x = "Population Density", y = "Life Expectancy")
```
As shown above, Life Expectancy appears to increase with Population Density, when plotted on the log scale. 

```{r}
#regression model
density_model <- lm(lifeExp ~ popden, 
                   data = combined1)
summary(density_model)
```
The above regression model shows that there is a relationship between Life Expectancy and Population Density. 


#part 2: Exploring Water Temperature on the Pacific Coast

```{r}
water <- read_html("https://www.nodc.noaa.gov/dsdt/cwtg/all_meanT.html")

water_south <-  html_nodes(water, css = ".reg:nth-child(21)") %>%
  html_table() %>%
  as.data.frame()


water_clean <- water_south %>%
  mutate(APR = (APR1.15 + APR16.30)/2) %>%
  mutate(MAY = (MAY1.15 + MAY16.31)/2) %>%
  mutate(JUN = (JUN1.15 + JUN16.30)/2) %>%
  mutate(JUL = (JUL1.15 + JUL16.31)/2) %>%
  mutate(AUG = (AUG1.15 + AUG16.31)/2) %>%
  mutate(SEP = (SEP1.15 + SEP16.30)/2) %>%
  mutate(OCT = (OCT1.15 + OCT16.31)/2) %>%
  select(Location, JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OCT, NOV, DEC)

water_month <- gather(water_clean, `JAN`, `FEB`, `MAR`, `APR`, `MAY`, `JUN`, `JUL`, `AUG`, `SEP`, `OCT`, `NOV`, `DEC` ,key = month, value = temp) 

water_month %>%
  ggplot(aes(month, temp)) +
  geom_point() + 
  labs(title = "Average Water Temp by Month, Southern CA", x = "Month", y = "Average Water Temp")
```

```{r}
water_season <- water_clean %>%
  mutate(Winter = (JAN +FEB +DEC)/3, 
         Spring = (MAR+APR+MAY)/3, 
         Summer = (JUN+JUL+AUG)/3, 
         Fall = (SEP+OCT+NOV)/3) %>%
  select(Location, Winter, Spring, Summer, Fall) %>%
  gather(`Winter`, `Spring`, `Summer`, `Fall`,key = season, value = temp)

water_season %>%
  ggplot(aes(season, temp)) +
  geom_boxplot() + 
  labs(title = "Boxplot of Avg Temperatures per Season", x = "Season", y = "Temperature")
  
water_avg <- water_clean %>%
  mutate(Avg = (JAN + FEB + MAR + APR + MAY + JUN + JUL + AUG + SEP + OCT + NOV + DEC)/12) %>%
  select(Location, Avg)
```

```{r}
temp_model <- lm(temp ~ season, 
                   data = water_season)
summary(temp_model)
```

